// Placeholder for displaying video thumbnails, views and duration until api fetching can be implemented

export const videos = [
  {
    id: "1",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 6345363476,
    postedAt: new Date("2024-01-01"),
    duration: 125634,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "2",
    title: "No, THIS video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 9345363476,
    postedAt: new Date("2024-01-01"),
    duration: 12,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "3",
    title: "MY video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 10045363476,
    postedAt: new Date("2024-01-01"),
    duration: 12,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "4",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 12,
    postedAt: new Date("2024-01-01"),
    duration: 1234354353,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "5",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 433765,
    postedAt: new Date("2024-01-01"),
    duration: 50000,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "6",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 6345363476,
    postedAt: new Date("2024-01-01"),
    duration: 12,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "7",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 6345363476,
    postedAt: new Date("2024-01-01"),
    duration: 12,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "8",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 6345363476,
    postedAt: new Date("2024-01-01"),
    duration: 12,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "9",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 6345363476,
    postedAt: new Date("2024-01-01"),
    duration: 12,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
  {
    id: "10",
    title: "this video will CHANGE you FOREVER",
    channel: {
      name: "John Doe",
      id: "JohnDoe",
      profileUrl: "/Yoo-video-logo.png",
    },
    views: 6345363476,
    postedAt: new Date("2024-01-01"),
    duration: 12,
    thumbnailUrl: "/Yoo-video-logo.png",
    videoUrl: "/watch?v=1",
  },
];
